Taj= input("Taj when is your birthday")
Josh= input("Josh when is your birthday")
Aaron= input("Aaron when is your birthday")
Fateh= input("Fateh when is your birthday")
Atinav= input("Atinav when is your birthday")
print("Taj birthday is on",Taj)
print("Josh birthday is on",Josh)
print("Aaron birthday is on",Aaron)
print("Fateh birthday is on",Fateh)
print("Atinav birthday is on",Atinav)